# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-16 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name': 'business', 'verbose_name_plural': 'businesses'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.TextField(max_length=140),
        ),
    ]
