# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-16 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20151116_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='transition_time',
        ),
    ]
