# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-16 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_service_transition_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='photo',
            field=models.ImageField(null=True, upload_to=b'professionals'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_gallery', to='booking.Professional'),
        ),
    ]
