# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-16 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20151116_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('profesional', 'category', 'name')},
        ),
    ]
