# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-16 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20151116_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='end',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start',
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
